function out = aggregate_headroom_(~, metricsArray)
out = struct( ...
    'assumedFullScaleV', nan, ...
    'excitationPeakV', nan, ...
    'excitationHeadroomDb', nan, ...
    'excitationClippingLikely', false, ...
    'responsePeakV', nan, ...
    'responseHeadroomDb', nan, ...
    'responseFlatTopFraction', nan, ...
    'responseClippingLikely', false);
if isempty(metricsArray)
    return
end

out.assumedFullScaleV = metricsArray(1).assumedFullScaleV;
out.excitationPeakV = mean([metricsArray.excitationPeakV], 'omitnan');
out.excitationHeadroomDb = mean([metricsArray.excitationHeadroomDb], 'omitnan');
out.excitationClippingLikely = any([metricsArray.excitationClippingLikely]);
out.responsePeakV = mean([metricsArray.responsePeakV], 'omitnan');
out.responseHeadroomDb = mean([metricsArray.responseHeadroomDb], 'omitnan');
out.responseFlatTopFraction = mean([metricsArray.responseFlatTopFraction], 'omitnan');
out.responseClippingLikely = any([metricsArray.responseClippingLikely]);
end
