function s = conduction_delay_report(d, maxDelayMs)
% s = stimgen.calibration.Engine.conduction_delay_report(d, maxDelayMs)
% Full text of a standalone conduction delay probe, for the dialog shown
% after it runs.
%
% A failed probe gets more text than a successful one, and deliberately: the
% reading itself is two numbers, while a failure is only actionable once it
% says which of the two ways it failed -- nothing came back, or something
% came back that no delay within the search bound explains.
lines = {};
if d.valid
    lines{end+1} = sprintf('Delay            %.3f ms   (%d samples at %.10g Hz)', ...
        d.delay_s * 1e3, d.delay_samples, d.fs);
    lines{end+1} = sprintf('Equivalent path  %.3f m of air at %.1f m/s (%.1f °C)', ...
        d.path_m, d.speed_of_sound_ms, d.temperature_c);
    lines{end+1} = '';
    lines{end+1} = ['The path is an upper bound on the speaker-to-microphone distance, ' ...
        'not a measurement of it: the converters'' round-trip latency is inside the ' ...
        'delay and cannot be told apart from time of flight. A path well above the ' ...
        'actual distance means that latency dominates, which is normal for some ' ...
        'devices but worth knowing.'];
    lines{end+1} = '';
    lines{end+1} = ['The distance is only as good as the temperature it was ' ...
        'converted at: the speed of sound moves about 0.6 m/s per °C, so a ' ...
        'room 6 °C off the Ambient Temperature setting puts a 1% error on ' ...
        'the path. The delay itself does not depend on it.'];
elseif d.peak_v <= 10 * max(d.noise_v, eps)
    lines{end+1} = 'No click response.';
    lines{end+1} = '';
    lines{end+1} = ['The record holds nothing standing above its own noise, so there ' ...
        'is no response to time. Check that the speaker is driven and the ' ...
        'microphone is connected and powered, then raise Excitation Voltage if ' ...
        'the rig is simply quiet.'];
else
    lines{end+1} = sprintf('Response found, but no delay within %.1f ms explains it.', ...
        maxDelayMs);
    lines{end+1} = '';
    lines{end+1} = ['Something came back and it is well above the noise, but no lag ' ...
        'inside the search bound puts the click where the response actually sits. ' ...
        'The true delay is probably larger than the bound: raise the largest delay ' ...
        'to search and measure again.'];
end

% The evidence, on both paths: a valid reading is only as good as the
% response it was read from, and an invalid one is diagnosed from the same
% two numbers.
lines{end+1} = '';
lines{end+1} = sprintf('Click response   %.5f V peak over %.5f V noise', ...
    d.peak_v, d.noise_v);
lines{end+1} = sprintf('Correlation      %.3f at the chosen lag', d.corr);
if d.at_bound
    lines{end+1} = sprintf('                 correlation peaked on the %.1f ms bound', ...
        maxDelayMs);
end
lines{end+1} = sprintf('Measured         %s', ...
    char(datetime(d.measuredOn, Format='dd-MMM-yyyy HH:mm:ss')));

lines{end+1} = '';
lines{end+1} = ['This probe stands on its own and nothing consumes it: a tone ' ...
    'calibration or tone table test measures its own delay per acquisition, ' ...
    'because the latency need not repeat between records of different lengths.'];

s = strjoin(string(lines), newline);
end
