function build_toolbar_(obj)
% Quick-access toolbar mirroring the most common File menu actions.
tb = uitoolbar(obj.Figure);

tip = @(key) stimgen.util.tooltip('CalibrationGui', key);

uipushtool(tb, Tooltip=tip('InitializeRuntimeTool'), ...
    Icon=stimgen.util.toolbar_icon('protocol'), ...
    ClickedCallback=@(~,~) obj.on_initialize_runtime_());

uipushtool(tb, Tooltip=tip('AttachAdapterTool'), ...
    Icon=stimgen.util.toolbar_icon('connect'), ...
    ClickedCallback=@(~,~) obj.on_attach_adapter_());

uipushtool(tb, Tooltip=tip('DisconnectTool'), ...
    Icon=stimgen.util.toolbar_icon('disconnect'), ...
    ClickedCallback=@(~,~) obj.on_disconnect_runtime_());

uipushtool(tb, Tooltip=tip('LoadTool'), Separator='on', ...
    Icon=stimgen.util.toolbar_icon('open'), ...
    ClickedCallback=@(~,~) obj.on_load_());

uipushtool(tb, Tooltip=tip('SaveTool'), ...
    Icon=stimgen.util.toolbar_icon('save'), ...
    ClickedCallback=@(~,~) obj.on_save_());

% Two ways of taking the session out of the window, grouped
% together: as words, and as a picture. Both mirror a File menu
% item, the way every other tool here does.
uipushtool(tb, Tooltip=tip('PrintSummary'), Separator='on', ...
    Icon=stimgen.util.toolbar_icon('summary'), ...
    ClickedCallback=@(~,~) obj.on_print_summary_());

% The whole window -- controls column included -- onto the
% clipboard in one press.
uipushtool(tb, Tooltip=tip('CopyWindowTool'), ...
    Icon=stimgen.util.toolbar_icon('camera'), ...
    ClickedCallback=@(~,~) obj.on_copy_window_());

uipushtool(tb, Tooltip=tip('QuickStartTool'), Separator='on', ...
    Icon=stimgen.util.toolbar_icon('help'), ...
    ClickedCallback=@(~,~) obj.on_show_quick_start_());

% The same wiki page, entered at the tour of this window. A book
% rather than a second question mark: the two tools answer
% different questions -- what calibration is, and what this
% control does -- and only the icons say which is which.
uipushtool(tb, Tooltip=tip('GuiGuideTool'), ...
    Icon=stimgen.util.toolbar_icon('wiki'), ...
    ClickedCallback=@(~,~) obj.on_show_gui_guide_());

obj.build_display_tools_(tb, tip);
end
