function create_settings_dialogs_(obj)
% The three Options windows. Each is a stimgen.calibration.
% SettingsDialog: built on demand from the build_*_dialog_ rows
% below, raised rather than duplicated when reopened, kept in
% step with the engine by its sync_*_dialog_, and closed with
% this window. Sizes and offsets place each over the controls
% column, below the top of the main window.
obj.HardwareDialog_ = stimgen.calibration.SettingsDialog( ...
    "Hardware and Analysis Settings", [400 334], [40 426], ...
    {24 24 24 12 20 24 24 12 20 24 24 26}, ...
    @(g) obj.build_hardware_dialog_(g), @() obj.sync_hardware_dialog_());
% The delay window's fifth row is its wrapped hint, with a line's
% slack over what the text needs at the default font, since a rig
% running a larger system font wraps it further.
obj.DelayDialog_ = stimgen.calibration.SettingsDialog( ...
    "Conduction Delay Settings", [420 242], [70 360], ...
    {24 24 8 24 76 26}, ...
    @(g) obj.build_delay_dialog_(g), @() obj.sync_delay_dialog_());
obj.ExcitationDialog_ = stimgen.calibration.SettingsDialog( ...
    "Excitation Settings", [380 102], [55 184], ...
    {24 24 26}, ...
    @(g) obj.build_excitation_dialog_(g), @() obj.sync_excitation_dialog_());
end
