function s = lut_spec_(obj, kind)
% s = lut_spec_(obj, kind)
% What the tone and click lookup-table actions differ in, so one sweep
% action (on_calibrate_lut_/run_calibrate_lut_) and one test action
% (on_test_lut_/run_test_lut_) serve both buttons of each pair. They used to
% be four near-identical pairs of methods that differed only in these
% fields.
%
% kind is "tone" or "click". Points are typed in the GUI's unit (Hz for
% tones, ms for clicks) and divided by GuiPerEngineUnit to reach the
% engine's (Hz, seconds).
switch kind
    case "tone"
        s.Label = 'Tone';
        s.Name  = 'tone';
        s.GuiPerEngineUnit = 1;
        % prompt_vector_parameter_ arguments, before includeRefinement
        s.SweepPrompt = {'toneFreqs', 'toneRepeats', "Tone Frequencies (Hz)", ...
            'DlgToneFrequencies', 'Tone Calibration'};
        s.Calibrate = @(x, n) obj.Engine.calibrate_tones(x, n);
        s.Refine    = @(maxIt, tol, n) obj.Engine.refine_tones( ...
            MaxIterations=maxIt, ToleranceDb=tol, RepeatCount=n);
        % The window opens with both lists empty, which hands the choice to
        % Engine.test_tones: the midpoints between LUT points, at
        % NormativeValue and 10/20 dB below it. Those defaults are the
        % interesting ones, so it opens ready to run.
        s.TestPrompt = {'Test Tone Lookup Table', 'tone', ...
            "Test Frequencies (Hz)", 'DlgTestToneFrequencies', ...
            "Requested Levels (dB SPL)", 'DlgTestToneLevels', ...
            'toneTestFreqs', 'toneTestLevels', 'toneTestRepeats'};
        s.Test   = @(x, levels, n) obj.Engine.test_tones(x, levels, RepeatCount=n);
        s.XField = 'frequency';
        s.Verdict = @(r, verdict) sprintf( ...
            'Tone LUT test %s (%s table): worst error %.2f dB at %.0f Hz / %g dB SPL, bias %+.2f dB (tolerance %.1f dB).', ...
            verdict, r.lut_source, r.max_abs_error_db, r.worst.frequency, ...
            r.worst.level_db, r.bias_db, r.tolerance_db);
        s.Advice = ['Levels are not being reproduced within ' ...
            'tolerance. A uniform bias usually means the reference measurement ' ...
            'moved since the sweep; errors at scattered frequencies ' ...
            'mean the table is too sparse to interpolate through -- recalibrate tones ' ...
            'with a finer frequency list.'];
        s.AlertTitle = 'Tone LUT Test Failed';

    case "click"
        s.Label = 'Click';
        s.Name  = 'click';
        s.GuiPerEngineUnit = 1e3;   % typed in ms, the engine takes seconds
        s.SweepPrompt = {'clickDurationsMs', 'clickRepeats', "Click Durations (ms)", ...
            'DlgClickDurations', 'Click Calibration'};
        s.Calibrate = @(x, n) obj.Engine.calibrate_clicks(x, n);
        s.Refine    = @(maxIt, tol, n) obj.Engine.refine_clicks( ...
            MaxIterations=maxIt, ToleranceDb=tol, RepeatCount=n);
        % Both lists empty hands the choice to Engine.test_clicks, as for
        % tones. Durations are in milliseconds here, as they are for the
        % click sweep itself.
        s.TestPrompt = {'Test Click Lookup Table', 'click', ...
            "Test Click Durations (ms)", 'DlgTestClickDurations', ...
            "Requested Levels (dB peSPL)", 'DlgTestClickLevels', ...
            'clickTestDurationsMs', 'clickTestLevels', 'clickTestRepeats'};
        s.Test   = @(x, levels, n) obj.Engine.test_clicks(x, levels, RepeatCount=n);
        s.XField = 'duration';
        s.Verdict = @(r, verdict) sprintf( ...
            'Click LUT test %s: worst error %.2f dB at %.1f \x00B5s / %g dB peSPL, bias %+.2f dB (tolerance %.1f dB).', ...
            verdict, r.max_abs_error_db, r.worst.duration * 1e6, ...
            r.worst.level_db, r.bias_db, r.tolerance_db);
        s.Advice = ['Levels are not being reproduced within ' ...
            'tolerance. A uniform bias usually means the reference measurement ' ...
            'moved since the sweep; errors at scattered durations ' ...
            'mean the table is too sparse to interpolate through -- recalibrate ' ...
            'clicks with a finer duration list. Very short clicks are the first to ' ...
            'fail on SNR, since they put little energy into the room.'];
        s.AlertTitle = 'Click LUT Test Failed';

    otherwise
        error('stimgen:calibration:CalibrationGui:badLutKind', ...
            'Lookup-table kind must be "tone" or "click", not "%s".', kind);
end
end
