function on_measure_reference_(obj)
if ~obj.apply_controls_to_engine_()
    return
end

% The step records only -- the tone comes from an acoustic
% calibrator on the microphone -- so the rig has to be set up by
% hand before the recording starts. Confirming here is what makes
% that sequence explicit instead of a silent prerequisite.
msg = sprintf([ ...
    'Place the acoustic calibrator (e.g. PCB CAL150) on the microphone ' ...
    'and switch it on.\n\n' ...
    'It must produce %g Hz at %g dB SPL, matching the Reference ' ...
    'Frequency and Reference Level fields.\n\n' ...
    'Nothing is played through the speaker: the microphone is recorded ' ...
    'for one second and the calibrator sets the scale.'], ...
    obj.Engine.ReferenceFrequency, obj.Engine.ReferenceLevel);
choice = uiconfirm(obj.Figure, msg, 'Measure Reference', ...
    Options={'Record', 'Cancel'}, DefaultOption=1, CancelOption=2, ...
    Icon='info');
if ~strcmp(choice, 'Record')
    obj.set_status_('Reference measurement cancelled.', false);
    return
end

obj.with_busy_state_(@() obj.run_measure_reference_(), 'Recording calibrator...');
end
