function [durs, levels, repeatCount, wasCancelled] = prompt_click_test_parameters_(obj)
% Collect the duration/level grid for the click LUT test. Both
% lists default to empty, which hands the choice to
% Engine.test_clicks: the midpoints between LUT points, at
% NormativeValue and 10/20 dB below it. Durations are in
% milliseconds here, as they are for the click sweep itself.
[durs, levels, repeatCount, wasCancelled] = obj.prompt_test_grid_( ...
    'Test Click Lookup Table', 'click', ...
    "Test Click Durations (ms)", 'DlgTestClickDurations', ...
    "Requested Levels (dB peSPL)", 'DlgTestClickLevels', ...
    'clickTestDurationsMs', 'clickTestLevels', 'clickTestRepeats');
end
