function [source, opts, wasCancelled] = prompt_filter_parameters_(obj)
% Collect equalizer design options. Everything except the source is
% returned as a name-value struct for Engine.design_filter, so the
% window stays a thin front end to that argument list. Choices are
% dropdowns and numbers are numeric fields, so only the frequency
% range (two numbers or nothing) and the rate/hardware pairing
% need checking, and both are checked before the window closes.
%
% The design rate is offered here rather than as a settings field
% because it belongs to the filter, not to the measurement: the LUT
% is in Hz and volts and holds at any rate, while the taps fitted to
% it only realize the designed response at the rate they were cut
% for. Naming the hardware rate in the label makes an intentional
% override obvious and an accidental one unlikely. Shown at full
% precision: typing back a %g-rounded 24414.1 for a 24414.0625 Hz
% converter designs a filter the rate guard refuses.
tip = @(k) stimgen.util.tooltip('CalibrationGui', k);
fsHardware = obj.Engine.Fs;
if fsHardware > 0
    rateLabel = sprintf('Design Sample Rate (Hz; 0 = %.10g)', fsHardware);
else
    rateLabel = 'Design Sample Rate (Hz; required)';
end

specs = [ ...
    param_spec_("source", "LUT Source", "dropdown", ...
        pref_choice_(obj.get_pref_('filterSource', 'auto'), ["auto" "tone" "swept_sine"], "auto"), ...
        Items=["auto" "tone" "swept_sine"], Tip=tip('DlgFilterSource')), ...
    param_spec_("nCoef", "Number of Coefficients (0 = auto)", "integer", ...
        pref_number_(obj.get_pref_('filterNumCoefficients', '0'), 0, [0 1e6], false), ...
        Limits=[0 1e6], Format='%d', Tip=tip('DlgFilterNumCoefficients')), ...
    param_spec_("designMethod", "Design Method", "dropdown", ...
        pref_choice_(obj.get_pref_('filterDesignMethod', 'freqsamp'), ["freqsamp" "ls"], "freqsamp"), ...
        Items=["freqsamp" "ls"], Tip=tip('DlgFilterDesignMethod')), ...
    param_spec_("interpolation", "Interpolation", "dropdown", ...
        pref_choice_(obj.get_pref_('filterInterpolation', 'pchip'), ["pchip" "linear" "spline" "makima"], "pchip"), ...
        Items=["pchip" "linear" "spline" "makima"], Tip=tip('DlgFilterInterpolation')), ...
    param_spec_("frequencyScale", "Frequency Scale", "dropdown", ...
        pref_choice_(obj.get_pref_('filterFrequencyScale', 'log'), ["log" "linear"], "log"), ...
        Items=["log" "linear"], Tip=tip('DlgFilterFrequencyScale')), ...
    param_spec_("smoothing", "Smoothing (octaves; 0 = none)", "numeric", ...
        pref_number_(obj.get_pref_('filterSmoothingOctaves', '0'), 0, [0 10], false), ...
        Limits=[0 10], Format='%.4g', Tip=tip('DlgFilterSmoothing')), ...
    param_spec_("maxCorrection", "Max Correction Depth (dB; Inf = none)", "numeric", ...
        pref_number_(obj.get_pref_('filterMaxCorrectionDb', 'Inf'), Inf, [0 Inf], true), ...
        Limits=[0 Inf], LowerOpen=true, Format='%.4g', ...
        Tip=tip('DlgFilterMaxCorrection')), ...
    param_spec_("freqRange", "Frequency Range (Hz, lo hi; empty = LUT)", "text", ...
        obj.get_pref_('filterFrequencyRange', ''), Tip=tip('DlgFilterFrequencyRange'), ...
        Validate=@frequency_range_), ...
    param_spec_("sampleRate", rateLabel, "numeric", ...
        pref_number_(obj.get_pref_('filterSampleRate', '0'), 0, [0 Inf], false), ...
        Limits=[0 Inf], Format='%.10g', Tip=tip('DlgFilterSampleRate'))];

% The one check that needs two fields: no rate typed and none to
% fall back on.
check = @(v) require_rate_(v.sampleRate, fsHardware);

[v, ok, raw] = parameter_dialog_(obj.Figure, 'Design Equalization Filter', '', specs, check);
wasCancelled = ~ok;
source = "auto";
opts = struct();
if ~ok
    return
end

source = string(v.source);
opts.DesignMethod     = string(v.designMethod);
opts.Interpolation    = string(v.interpolation);
opts.FrequencyScale   = string(v.frequencyScale);
opts.SmoothingOctaves = v.smoothing;
opts.MaxCorrectionDb  = v.maxCorrection;
opts.FrequencyRange   = v.freqRange;
if v.nCoef > 0
    opts.NumCoefficients = v.nCoef;
end
if v.sampleRate > 0
    opts.SampleRate = v.sampleRate;
end

obj.set_pref_('filterSource',           char(source));
obj.set_pref_('filterNumCoefficients',  sprintf('%d', v.nCoef));
obj.set_pref_('filterDesignMethod',     char(opts.DesignMethod));
obj.set_pref_('filterInterpolation',    char(opts.Interpolation));
obj.set_pref_('filterFrequencyScale',   char(opts.FrequencyScale));
obj.set_pref_('filterSmoothingOctaves', sprintf('%.15g', v.smoothing));
obj.set_pref_('filterMaxCorrectionDb',  sprintf('%.15g', v.maxCorrection));
obj.set_pref_('filterFrequencyRange',   raw.freqRange);
obj.set_pref_('filterSampleRate',       sprintf('%.15g', v.sampleRate));
end
