function [duration, freqs, repeatCount, wasCancelled] = prompt_swept_sine_parameters_(obj)
% The window works in milliseconds; the returned duration is in
% seconds, as Engine.calibrate_swept_sine expects. The pref key
% carries a Ms suffix so pre-ms values are not reinterpreted.
tip = @(k) stimgen.util.tooltip('CalibrationGui', k);
specs = [ ...
    param_spec_("durationMs", "Sweep Duration (ms)", "numeric", ...
        pref_number_(obj.get_pref_('sweptSineDurationMs', '1000'), 1000, [0 600000], true), ...
        Limits=[0 600000], LowerOpen=true, Format='%.6g', ...
        Tip=tip('DlgSweptDuration')), ...
    param_spec_("freqs", "Analysis Frequencies (Hz)", "text", ...
        obj.get_pref_('sweptSineFreqs', ''), Tip=tip('DlgSweptFrequencies'), ...
        Validate=@(t) vector_or_empty_(t, 'swept sine frequencies')), ...
    param_spec_("repeats", "Number of Averages", "integer", ...
        pref_number_(obj.get_pref_('sweptSineRepeats', '4'), 4, [1 1000], false), ...
        Limits=[1 1000], Format='%d', Tip=tip('DlgRepeats'))];

[v, ok, raw] = parameter_dialog_(obj.Figure, 'Swept Sine Calibration', '', specs);
wasCancelled = ~ok;
if ~ok
    duration = 1;
    freqs = [];
    repeatCount = 4;
    return
end
duration    = v.durationMs / 1e3;
freqs       = v.freqs;
repeatCount = v.repeats;
obj.set_pref_('sweptSineDurationMs', sprintf('%.15g', v.durationMs));
obj.set_pref_('sweptSineFreqs', raw.freqs);
obj.set_pref_('sweptSineRepeats', sprintf('%d', repeatCount));
end
