function [p, wasCancelled] = prompt_background_parameters_(obj)
% Collect the capture parameters, before the busy state: a typed
% window that will not close on a value the engine would refuse,
% so a typo is corrected in place rather than surfacing as a red
% Calibration Error after the button has been pressed. The
% physical prerequisites head it: unlike a sweep, this
% measurement is only meaningful when the rig is in the state an
% experiment runs in, and nothing else in the window can say so.
tip = @(k) stimgen.util.tooltip('CalibrationGui', k);
specs = [ ...
    param_spec_("duration", "Recording Duration (s)", "numeric", ...
        pref_number_(obj.get_pref_('backgroundDurationS', '2'), 2, [0 3600], true), ...
        Limits=[0 3600], LowerOpen=true, Format='%.4g', ...
        Tip=tip('DlgBackgroundDuration')), ...
    param_spec_("records", "Number of Records", "integer", ...
        pref_number_(obj.get_pref_('backgroundRecords', '3'), 3, [1 1000], false), ...
        Limits=[1 1000], Format='%d', Tip=tip('DlgBackgroundRecords')), ...
    param_spec_("prominence", "Tonal Peak Prominence (dB)", "numeric", ...
        pref_number_(obj.get_pref_('backgroundProminenceDb', '6'), 6, [0 200], true), ...
        Limits=[0 200], LowerOpen=true, Format='%.3g', ...
        Tip=tip('DlgBackgroundProminence'))];
intro = ['Nothing is played during this measurement. Take the acoustic ' ...
    'calibrator off the microphone, put the microphone where it sits ' ...
    'during an experiment, and leave the rig running as it normally does.'];

[p, ok] = parameter_dialog_(obj.Figure, 'Measure Background', intro, specs);
wasCancelled = ~ok;
if ok
    obj.set_pref_('backgroundDurationS', sprintf('%.15g', p.duration));
    obj.set_pref_('backgroundRecords', sprintf('%d', p.records));
    obj.set_pref_('backgroundProminenceDb', sprintf('%.15g', p.prominence));
end
end
