function [freqs, levels, repeatCount, wasCancelled] = prompt_tone_test_parameters_(obj)
% Collect the frequency/level grid for the tone LUT test. Both
% lists default to empty, which hands the choice to Engine.test_tones:
% the midpoints between LUT points, at NormativeValue and 10/20 dB
% below it. Those defaults are the interesting ones, so the window
% opens ready to run.
[freqs, levels, repeatCount, wasCancelled] = obj.prompt_test_grid_( ...
    'Test Tone Lookup Table', 'tone', ...
    "Test Frequencies (Hz)", 'DlgTestToneFrequencies', ...
    "Requested Levels (dB SPL)", 'DlgTestToneLevels', ...
    'toneTestFreqs', 'toneTestLevels', 'toneTestRepeats');
end
