function report_refinement_(obj, r, whatLabel)
% Status line (and an alert on non-convergence) after an
% iterative refinement. The residual is the last test's verdict,
% so what is reported is what the committed table was measured
% to do -- not what the corrections were hoped to achieve.
if r.converged
    obj.set_status_(sprintf( ...
        ['%s calibration refined: worst error %.2f dB after %d test ' ...
         'pass(es), within the %.2g dB target.'], ...
        whatLabel, r.final_max_abs_error_db, r.n_iterations, ...
        r.tolerance_db), false);
    return
end

msg = sprintf( ...
    ['%s calibration refined from %.2f to %.2f dB worst error, but did ' ...
     'not reach the %.2g dB target in %d test pass(es).'], ...
    whatLabel, r.initial_max_abs_error_db, r.final_max_abs_error_db, ...
    r.tolerance_db, r.n_iterations);
obj.set_status_(msg, true);
uialert(obj.Figure, sprintf(['%s\n\nThe table keeps the last verified ' ...
    'corrections, so nothing was lost. A residual that will not shrink ' ...
    'is usually measurement spread: raise the number of averages, or ' ...
    'loosen the target. If %d point(s) were left uncorrected as ' ...
    'unreliable, they are unreachable at the normative level or too ' ...
    'quiet to measure -- see the log.'], msg, r.n_unreliable), ...
    'Refinement Did Not Converge', Icon='warning');
end
